/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 91887
 */
import java.sql.*;
public class addbus extends javax.swing.JFrame {

    /**
     * Creates new form addbus
     */
    public addbus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addbustitlee = new javax.swing.JLabel();
        Sourcepoint = new javax.swing.JLabel();
        getsourcepoint = new javax.swing.JTextField();
        Destiination = new javax.swing.JLabel();
        getdestination = new javax.swing.JTextField();
        Drivername = new javax.swing.JLabel();
        getdrivername = new javax.swing.JTextField();
        Firststop = new javax.swing.JLabel();
        get1stop = new javax.swing.JTextField();
        Secondstop = new javax.swing.JLabel();
        get2stop = new javax.swing.JTextField();
        Thirdstop = new javax.swing.JLabel();
        get3stop = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        getsdate = new javax.swing.JTextField();
        Startdate = new javax.swing.JLabel();
        Endingdate = new javax.swing.JLabel();
        getedate = new javax.swing.JTextField();
        Seaterseats = new javax.swing.JLabel();
        getseaterseats = new javax.swing.JTextField();
        Sleeperseats = new javax.swing.JLabel();
        getsleeperseats = new javax.swing.JTextField();
        seaterprice = new javax.swing.JLabel();
        getseaterprice = new javax.swing.JTextField();
        sleeperprice = new javax.swing.JLabel();
        getsleeperprice = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bid = new javax.swing.JTextField();
        stime = new javax.swing.JLabel();
        starttime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        endtime = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addbustitlee.setBackground(new java.awt.Color(255, 255, 0));
        addbustitlee.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        addbustitlee.setForeground(new java.awt.Color(0, 0, 204));
        addbustitlee.setText("MSD BUS TRAVELS");

        Sourcepoint.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Sourcepoint.setText("Source point:");

        getsourcepoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getsourcepointActionPerformed(evt);
            }
        });

        Destiination.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Destiination.setText("Destination");

        getdestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getdestinationActionPerformed(evt);
            }
        });

        Drivername.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Drivername.setText("Drivername");

        getdrivername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getdrivernameActionPerformed(evt);
            }
        });

        Firststop.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Firststop.setText("First stop");

        get1stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get1stopActionPerformed(evt);
            }
        });

        Secondstop.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Secondstop.setText("Second stop");

        get2stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get2stopActionPerformed(evt);
            }
        });

        Thirdstop.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Thirdstop.setText("Third stop");

        get3stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get3stopActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        getsdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getsdateActionPerformed(evt);
            }
        });

        Startdate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Startdate.setText("S date");

        Endingdate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Endingdate.setText("E date");

        getedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getedateActionPerformed(evt);
            }
        });

        Seaterseats.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Seaterseats.setText("Seater seats");

        getseaterseats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getseaterseatsActionPerformed(evt);
            }
        });

        Sleeperseats.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Sleeperseats.setText("Sleeper seats");

        getsleeperseats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getsleeperseatsActionPerformed(evt);
            }
        });

        seaterprice.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        seaterprice.setText("Seater price");

        getseaterprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getseaterpriceActionPerformed(evt);
            }
        });

        sleeperprice.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        sleeperprice.setText("Sleeper price");

        getsleeperprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getsleeperpriceActionPerformed(evt);
            }
        });

        submit.setBackground(new java.awt.Color(0, 255, 255));
        submit.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 51, 102));
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setText("Bid");

        bid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidActionPerformed(evt);
            }
        });

        stime.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        stime.setText("Starttime");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setText("Endtime");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Firststop, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Secondstop, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sourcepoint, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Thirdstop, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(303, 303, 303)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seaterprice, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sleeperprice, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(39, 39, 39)
                                            .addComponent(bid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Destiination, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(getdrivername, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(getsourcepoint, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(getdestination, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(get1stop, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(get2stop, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(get3stop, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(Drivername, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Startdate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Seaterseats, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(stime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Endingdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                                    .addComponent(Sleeperseats)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(getseaterprice, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(getsleeperprice, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(getsleeperseats, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(getseaterseats, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(getedate, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(getsdate, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(starttime)
                            .addComponent(endtime))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(addbustitlee, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addbustitlee)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(getsdate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Startdate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getsourcepoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sourcepoint)
                            .addComponent(Endingdate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(starttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(endtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(submit)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(Destiination, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(getdestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(33, 33, 33)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(Drivername)
                                                        .addComponent(getdrivername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGap(7, 7, 7)))
                                    .addComponent(stime))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Firststop, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(get1stop))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Seaterseats)
                                    .addComponent(getseaterseats, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Sleeperseats, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(getsleeperseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(seaterprice)
                                    .addComponent(getseaterprice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Secondstop)
                                    .addComponent(get2stop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(sleeperprice)
                                            .addComponent(getsleeperprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Thirdstop)
                                            .addComponent(get3stop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(28, 28, 28))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(getedate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getsourcepointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getsourcepointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getsourcepointActionPerformed

    private void get3stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get3stopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_get3stopActionPerformed

    private void getsdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getsdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getsdateActionPerformed

    private void getedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getedateActionPerformed

    private void getseaterpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getseaterpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getseaterpriceActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
//TODO add your handling code here:
   String sourcepoint=getsourcepoint.getText();
   String destination=getdestination.getText(); 
   String drivername=getdrivername.getText();
   String firststop=get1stop.getText();
   String secondstop=get2stop.getText();
   String thirdstop=get3stop.getText();  
   String startdate=getsdate.getText();
   String enddate=getedate.getText();
   String seaterseats=getseaterseats.getText();
   String sleeperseats=getsleeperseats.getText();
   String seaterprice=getseaterprice.getText();
   String sleeperprice=getsleeperprice.getText();
   String BUSid=bid.getText();
   String stime=starttime.getText();
   String etime=endtime.getText();
   Connection conn = null;
       Statement stmt = null;
       try {
         try {
            Class.forName("com.mysql.jdbc.Driver");
         } catch (Exception e) {
            System.out.println(e);
      }
      conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/msdtravels", "root", "");
      System.out.println("Connection is created successfully:");
      stmt = (Statement) conn.createStatement();//insert into customer values (1,'name','email',customer,'number',0);
      String query1 = "INSERT INTO bus(bid,bdrivername,bsource,bdestination,bstop1,bstop2,bstop3,bstarttime,bstartdate,bendtime,benddate) VALUES ("+BUSid+",'"+drivername+"','"+sourcepoint+"','"+destination+"','"+firststop+"','"+secondstop+"','"+thirdstop+"','"+stime+"','"+startdate+"','"+etime+"','"+enddate+"')";
      stmt.executeUpdate(query1);
      System.out.println("Record is inserted in the table bus successfully..................");
      String query2="INSERT INTO busdetails(bid,seaternos,sleepernos,seateramount,sleeperamount) VALUES ("+BUSid+",'"+seaterseats+"','"+sleeperseats+"','"+seaterprice+"','"+sleeperprice+"')";
      stmt.executeUpdate(query2);
      System.out.println("bus details entered");
       } catch (SQLException excep) {
         excep.printStackTrace();
      } catch (Exception excep) { 
         excep.printStackTrace();
      } finally {
         try {
            if (stmt != null)
               conn.close();
         } catch (SQLException se) {}
         try {
            if (conn != null)
               conn.close();
         } catch (SQLException se) {
            se.printStackTrace();
         }  
      }
      System.out.println("Please check it in the MySQL Table......... ……..");
   
   
   
   
   
   
   
    }//GEN-LAST:event_submitActionPerformed

    private void getdestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getdestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getdestinationActionPerformed

    private void get2stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get2stopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_get2stopActionPerformed

    private void bidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bidActionPerformed

    private void getdrivernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getdrivernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getdrivernameActionPerformed

    private void get1stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get1stopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_get1stopActionPerformed

    private void getsleeperpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getsleeperpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getsleeperpriceActionPerformed

    private void getsleeperseatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getsleeperseatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getsleeperseatsActionPerformed

    private void getseaterseatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getseaterseatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getseaterseatsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new editbus().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addbus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addbus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addbus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addbus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addbus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Destiination;
    private javax.swing.JLabel Drivername;
    private javax.swing.JLabel Endingdate;
    private javax.swing.JLabel Firststop;
    private javax.swing.JLabel Seaterseats;
    private javax.swing.JLabel Secondstop;
    private javax.swing.JLabel Sleeperseats;
    private javax.swing.JLabel Sourcepoint;
    private javax.swing.JLabel Startdate;
    private javax.swing.JLabel Thirdstop;
    private javax.swing.JLabel addbustitlee;
    private javax.swing.JTextField bid;
    private javax.swing.JTextField endtime;
    private javax.swing.JTextField get1stop;
    private javax.swing.JTextField get2stop;
    private javax.swing.JTextField get3stop;
    private javax.swing.JTextField getdestination;
    private javax.swing.JTextField getdrivername;
    private javax.swing.JTextField getedate;
    private javax.swing.JTextField getsdate;
    private javax.swing.JTextField getseaterprice;
    private javax.swing.JTextField getseaterseats;
    private javax.swing.JTextField getsleeperprice;
    private javax.swing.JTextField getsleeperseats;
    private javax.swing.JTextField getsourcepoint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel seaterprice;
    private javax.swing.JLabel sleeperprice;
    private javax.swing.JTextField starttime;
    private javax.swing.JLabel stime;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
